services:
  - type: worker
    name: us-trading-crypto-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: cd backend && python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: PYTHON_VERSION
        value: 3.12.0
